name    'puppetlabs-solarisnic'
version '0.0.1'
source 'UNKNOWN'
author 'puppetlabs'
license 'Apache 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.3.0'
